// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // El cliente generado de Prisma usa imports "nodenext" (.js que resuelven
    // a .ts): node por sí solo no sabe resolver eso, así que compilamos con
    // tsc antes de correr (ver el script "db:seed" en package.json).
    seed: "npm run db:seed --silent",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
